export default function sitemap() {
  const base = 'https://www.cotaparaguai.com.br'
  return [
    { url: base,                                              lastModified: new Date(), changeFrequency: 'hourly',  priority: 1.0 },
    { url: `${base}/calculadora-dolar-paraguai`,             lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/melhor-forma-pagamento-paraguai`,        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/celular-paraguai`,                      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/samsung-paraguai`,                      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/airpods-paraguai`,                      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/macbook-paraguai`,                      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/whisky-paraguai`,                       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/notebook-paraguai`,                     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/lojas-paraguai`,                        lastModified: new Date(), changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${base}/samsung-paraguai`,                     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/airpods-paraguai`,                     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/macbook-paraguai`,                     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/celular-paraguai`,                      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/notebook-paraguai`,                     lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/quanto-de-imposto-pagar-no-paraguai`,   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/como-calcular-imposto-paraguai`,        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/cota-paraguai-via-terrestre`,           lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/imposto-iphone-paraguai`,               lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/eletronicos-paraguai`,                  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/perfume-paraguai`,                      lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/whisky-paraguai`,                       lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/nomad-paraguai`,                        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/limite-compras-paraguai`,               lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/como-declarar-paraguai`,                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/o-que-comprar-paraguai`,                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/quanto-custa-viajar-cidade-del-este`,   lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/seguro-viagem-paraguai`,                lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/duty-free-foz-do-iguacu`,               lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/buscar`,                              lastModified: new Date(), changeFrequency: 'daily',   priority: 0.9 },
    { url: `${base}/quanto-custa-iphone-paraguai`,         lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/ps5-paraguai`,                        lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/perfume-chanel-paraguai`,             lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/alfandega-paraguai`,                  lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/lojas-ciudad-del-este`,              lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/brasil-vs-paraguai`,                 lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/sobre`,                              lastModified: new Date(), changeFrequency: 'yearly',  priority: 0.6 },
    { url: `${base}/como-chegar-ciudad-del-este`,          lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/como-nao-cair-em-golpes-paraguai`,    lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guia-compras-paraguai`,               lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/privacidade`,                           lastModified: new Date(), changeFrequency: 'yearly',  priority: 0.3 },
  ]
}
